In [1]:
# Review Text — customer's written review.
# Rating — customer's star rating.
# Sentiment Score — score calculated from the review text.
# Normalized Sentiment — score converted to a range from 0 to 1.
# Sentiment — Positive, Neutral, or Negative.

In [3]:
!pip install vaderSentiment

Collecting vaderSentiment
  Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl.metadata (572 bytes)
Requirement already satisfied: requests in d:\anaconda\lib\site-packages (from vaderSentiment) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\anaconda\lib\site-packages (from requests->vaderSentiment) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda\lib\site-packages (from requests->vaderSentiment) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda\lib\site-packages (from requests->vaderSentiment) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda\lib\site-packages (from requests->vaderSentiment) (2026.7.22)
Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
Installing collected packages: vaderSentiment
Successfully installed vaderSentiment-3.3.2

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [5]:
data = pd.read_csv("Womens Clothing E-Commerce Reviews.csv")

In [6]:
data

,Unnamed: 0,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
0,0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates
1,1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses
2,2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
3,3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
4,4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses
...,...,...,...,...,...,...,...,...,...,...,...
23481,23481,1104,34,Great dress for many occasions,I was very happy to snag this dress at such a ...,5,1,0,General Petite,Dresses,Dresses
23482,23482,862,48,Wish it was made of cotton,"It reminds me of maternity clothes. soft, stre...",3,1,0,General Petite,Tops,Knits
23483,23483,1104,31,"Cute, but see through","This fit well, but the top was very see throug...",3,0,1,General Petite,Dresses,Dresses
23484,23484,1084,28,"Very cute dress, perfect for summer parties an...",I bought this dress for a wedding i have this ...,3,1,2,General,Dresses,Dresses
23485,23485,1104,52,Please make more like this one!,This dress in a lovely platinum is feminine an...,5,1,22,General Petite,Dresses,Dresses

In [7]:
data.shape

(23486, 11)

In [9]:
data.columns.tolist()

['Unnamed: 0',
 'Clothing ID',
 'Age',
 'Title',
 'Review Text',
 'Rating',
 'Recommended IND',
 'Positive Feedback Count',
 'Division Name',
 'Department Name',
 'Class Name']

In [10]:
data.isnull().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [12]:
data.describe()

,Unnamed: 0,Clothing ID,Age,Rating,Recommended IND,Positive Feedback Count
count,23486.000000,23486.000000,23486.000000,23486.000000,23486.000000,23486.000000
mean,11742.500000,918.118709,43.198544,4.196032,0.822362,2.535936
std,6779.968547,203.298980,12.279544,1.110031,0.382216,5.702202
min,0.000000,0.000000,18.000000,1.000000,0.000000,0.000000
25%,5871.250000,861.000000,34.000000,4.000000,1.000000,0.000000
50%,11742.500000,936.000000,41.000000,5.000000,1.000000,1.000000
75%,17613.750000,1078.000000,52.000000,5.000000,1.000000,3.000000
max,23485.000000,1205.000000,99.000000,5.000000,1.000000,122.000000

In [13]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               23486 non-null  int64
 1   Clothing ID              23486 non-null  int64
 2   Age                      23486 non-null  int64
 3   Title                    19676 non-null  str
 4   Review Text              22641 non-null  str
 5   Rating                   23486 non-null  int64
 6   Recommended IND          23486 non-null  int64
 7   Positive Feedback Count  23486 non-null  int64
 8   Division Name            23472 non-null  str
 9   Department Name          23472 non-null  str
 10  Class Name               23472 non-null  str
dtypes: int64(6), str(5)
memory usage: 9.5 MB

Create Sentiment Score

In [19]:
analyzer = SentimentIntensityAnalyzer()
data['Reviw Text'] = data['Review Text'].fillna("")
data["Sentiment_Score"] = data["Reviw Text"].apply(
        lambda x: analyzer.polarity_scores(x)["compound"]
)

In [20]:
data.head()

,Unnamed: 0,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name,Reviw Text,sentiment_score,Sentiment_score,Sentiment_Score
0,0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates,Absolutely wonderful - silky and sexy and comf...,0.8932,0.8932,0.8932
1,1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses,Love this dress! it's sooo pretty. i happene...,0.9729,0.9729,0.9729
2,2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses,I had such high hopes for this dress and reall...,0.9208,0.9208,0.9208
3,3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants,"I love, love, love this jumpsuit. it's fun, fl...",0.5727,0.5727,0.5727
4,4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses,This shirt is very flattering to all due to th...,0.9291,0.9291,0.9291

Create Sentiment and Normalized Score

In [21]:
data["Sentiment"] = data["Sentiment_Score"].apply(
    lambda x: "Positive" if x >= 0.05
    else "Negative" if x <= -0.05
    else "Neutral"
)

data["Normalized_Sentiment"] = (
    data["Sentiment_Score"] + 1
) / 2

data[["Review Text", "Sentiment_Score",
      "Sentiment", "Normalized_Sentiment"]].head()

,Review Text,Sentiment_Score,Sentiment,Normalized_Sentiment
0,Absolutely wonderful - silky and sexy and comf...,0.8932,Positive,0.94660
1,Love this dress! it's sooo pretty. i happene...,0.9729,Positive,0.98645
2,I had such high hopes for this dress and reall...,0.9208,Positive,0.96040
3,"I love, love, love this jumpsuit. it's fun, fl...",0.5727,Positive,0.78635
4,This shirt is very flattering to all due to th...,0.9291,Positive,0.96455

In [22]:
data.to_csv("clothing_sentiment.csv", index=False)